server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/propshare
    username: postgres
    password: 200030@aA
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true